name = "actis-auth"
main = "src/index.js"
compatibility_date = "2026-08-14"
keep_vars = true

[[kv_namespaces]]
binding = "AUTH_KV"
id = "e1f10565b85349e399c459a7e79f5468"

[observability]
enabled = true

[observability.logs]
enabled = true
